/**
 * sequencing , there's an specific order or else the sprite would be messed up
 */
/**
 * Selection:  Games over and have to go back to the start
 */
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile0`, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    game.over(false)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    boo.vy = -20
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.floorDark3, function (sprite, location) {
    game.over(false)
})
/**
 * Iteration is happening here,
 */
let boo: Sprite = null
scene.setBackgroundColor(11)
game.splash("will you help boo ")
boo = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    .........fffff..........
    .......ffb1111ff........
    ......fb1111111bf.......
    ......f111111111f.......
    .....ffff1111111df......
    ....fb111c1dd111df......
    ....ffb1b1fdcf11bf......
    .....ffbfbfb11111f......
    ......ffffcfdb1b1f......
    .......fcccfcfbfbf......
    ........ffffffffff......
    .........ffffff.........
    .........ffffff.........
    .....f..fffffff.........
    .....fffffffff..........
    ......fffffff...........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
pause(100)
boo.setPosition(6, 9)
tiles.setCurrentTilemap(tilemap`level5`)
scene.cameraFollowSprite(boo)
forever(function () {
    boo.setImage(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111cfbf.......
        ........ffb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `)
    pause(200)
    boo.setImage(img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        .......ffb1111ff........
        ......fb1111111bf.......
        ......f111111111f.......
        .....ffff1111111df......
        ....fb111c1dd111df......
        ....ffb1b1fdcf11bf......
        .....ffbfbfb11111f......
        ......ffffcfdb1b1f......
        .......fcccfcfbfbf......
        ........ffffffffff......
        .........ffffff.........
        .........ffffff.........
        .....f..fffffff.........
        .....fffffffff..........
        ......fffffff...........
        ........................
        ........................
        ........................
        ........................
        `)
    pause(200)
    boo.ay += 10
    boo.ax += 5
})
